name: png_optimizer
description: A transformer to optimize png images.
version: 0.0.1-pre.0
repository: https://github.com/hadysata/png_optimizer/
homepage: https://github.com/hadysata/png_optimizer/

environment:
  sdk: ^3.4.0-0

dependencies:
  args: ^2.4.2
  image: ^4.1.7

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
